update tests to be compatible with iha refactor

diff --git a/playbooks/09_kdump.yaml b/playbooks/09_kdump.yaml
--- a/playbooks/09_kdump.yaml
+++ b/playbooks/09_kdump.yaml
@@ -21,6 +21,16 @@
     name: "09-test-kdump-before-evacuation"
     _final_action: "{{ final_action | default('reboot') }}"
   tasks:
+    - shell: |
+        oc rsh deployment/instanceha-0 bash -c 'wc -l /var/lib/instanceha/instanceha.py' |awk '{print $1}'
+      register: size
+
+    - name: Define Variable
+      set_fact:
+          _final_action: "poweroff"
+      when:
+        - size.stdout |int < 1000
+
     - name: 09 Create results file (failure)
       ansible.builtin.template:
         src: templates/iha-tests-results.xml.j2
@@ -95,7 +105,10 @@
         C0N=$(echo "{{ hostvars['controller-0']['compute0'] }}"|cut -d. -f1)
         C1N=$(echo "{{ hostvars['controller-0']['compute1'] }}"|cut -d. -f1)
 
-        ssh root@$C0N "ifdown vlan20 || true; mv /etc/sysconfig/network-scripts/ifcfg-vlan20 /root/ifcfg-vlan20 || true;
+        ssh root@$C0N "cp /etc/NetworkManager/system-connections/vlan20-port.nmconnection /root/ || true;
+                       cp /etc/NetworkManager/system-connections/vlan20-if.nmconnection /root/ || true;
+                       nmcli c delete vlan20-port || true;
+                       nmcli c delete vlan20-if || true;
                        echo 'DEVICE=eth1.20' > /etc/sysconfig/network-scripts/ifcfg-eth1.20;
                        echo 'MTU=1496' >> /etc/sysconfig/network-scripts/ifcfg-eth1.20;
                        echo 'ONBOOT=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth1.20;
@@ -109,7 +122,10 @@
                        echo 'IPADDR=172.17.0.100' >> /etc/sysconfig/network-scripts/ifcfg-eth1.20;
                        ifup eth1.20;
                        sed -i 's/GRUB_TIMEOUT=0/GRUB_TIMEOUT=60/g' /etc/default/grub ; grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg; reboot"
-        ssh root@$C1N "ifdown vlan20 || true; mv /etc/sysconfig/network-scripts/ifcfg-vlan20 /root/ifcfg-vlan20 || true;
+        ssh root@$C1N "cp /etc/NetworkManager/system-connections/vlan20-port.nmconnection /root/ || true;
+                       cp /etc/NetworkManager/system-connections/vlan20-if.nmconnection /root/ || true;
+                       nmcli c delete vlan20-port || true;
+                       nmcli c delete vlan20-if || true;
                        echo 'DEVICE=eth1.20' > /etc/sysconfig/network-scripts/ifcfg-eth1.20;
                        echo 'MTU=1496' >> /etc/sysconfig/network-scripts/ifcfg-eth1.20;
                        echo 'ONBOOT=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth1.20;
@@ -190,7 +206,7 @@
 
     - name: 09 Wait evacuation
       ansible.builtin.pause:
-        minutes: 12
+        minutes: 8
 
 - name: 09 Check evacuation
   hosts: controller-0
@@ -209,16 +225,26 @@
         msg: "vm c1 not evacuated, this should not happen"
       when: hypervisor3.stdout in hostvars['controller-0']['compute0']
 
-    - name: 09 check logs and see if we received the kdump msgs compute0
-      ansible.builtin.shell: |
-        oc logs $(oc get pods |grep instanceha| awk '{print $1}') |grep "{{ hostvars['controller-0']['compute0'] }}" |grep 'are kdumping'
-      register: grep
-      changed_when: false
+#    - name: 09 check logs and see if we received the kdump msgs compute0
+#      ansible.builtin.shell: |
+#        oc logs $(oc get pods |grep instanceha| awk '{print $1}') |grep "{{ hostvars['controller-0']['compute0'] }}" |grep 'fenced via kdump'
+#      register: grep
+#      changed_when: false
+#
 
-    - name: 09 fail if we did not see any kdump msg
-      ansible.builtin.fail:
-        msg: "KDUMP msg not received"
-      when: grep.rc != 0
+    - name: 99 check logs and see if we received the kdump msgs compute0
+      ansible.builtin.shell: |
+        oc logs deploy/instanceha-0 |grep "{{ hostvars['controller-0']['compute0'] }}"
+      register: logs
+      changed_when: false
+      retries: 60
+      delay: 10
+      until: "'are kdumping' in logs.stdout or 'fenced via kdump' in logs.stdout"
+
+#    - name: 09 fail if we did not see any kdump msg
+#      ansible.builtin.fail:
+#        msg: "KDUMP msg not received"
+#      when: grep.rc != 0
 
     - name: 09 save logs
       ansible.builtin.shell: oc logs deploy/instanceha-0 >> /home/zuul/iha-tests-results/{{ name }}.log
@@ -239,7 +265,17 @@
         host: "{{ compute0 }}"
       register: compute_0_status
       until: "'up' in compute_0_status.compute_services | map(attribute='state')"
-      retries: 20
+      retries: 60
+      delay: 10
+
+    - name: 09 Wait compute-0 to be enabled
+      openstack.cloud.compute_service_info:
+        cloud: default
+        binary: "nova-compute"
+        host: "{{ compute0 }}"
+      register: compute_0_status
+      until: "'enabled' in compute_0_status.compute_services | map(attribute='status')"
+      retries: 60
       delay: 10
 
     - name: 09 Wait compute-1 to be up
@@ -249,7 +285,17 @@
         host: "{{ compute1 }}"
       register: compute_1_status
       until: "'up' in compute_1_status.compute_services | map(attribute='state')"
-      retries: 20
+      retries: 60
+      delay: 10
+
+    - name: 09 Wait compute-1 to be enabled
+      openstack.cloud.compute_service_info:
+        cloud: default
+        binary: "nova-compute"
+        host: "{{ compute1 }}"
+      register: compute_1_status
+      until: "'enabled' in compute_1_status.compute_services | map(attribute='status')"
+      retries: 60
       delay: 10
 
     - name: 09 Cleanup kdump.conf on compute-0
